name: 'latex-build-langja'
description: 'latex build environment package for japanese'
author: 3rdJCG

inputs:
  root_file:
    description: The root LaTeX file to be compiled
    required: true
  working_directory:
    description: The working directory for the latex compiler to be invoked
  compiler:
    description: LaTeX engine to be used
    default: latexmk
  args:
    description: Extra arguments to be passed to the latex compiler
    default: "-pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode"
  extra-tex-package:
    description: Install extra packages by tlmgr
runs:
  using: 'docker'
  image: 'docker://3rdjcg/latex-ci-notojp:latest'
  args:
    - ${{ inputs.root_file }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.compiler }}
    - ${{ inputs.args }}
    - ${{ inputs.extra-tex-package }}